file_format: "1"
id: sml58
name: sml58
type: shield
url: https://github.com/kata0510/sml58
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - studio
siblings:
  - sml58_left
  - sml58_right
